### ISSUE TITLE
Deflate and Deflate64 appear to still be using LZMA and cannot be opened by Windows File Explorer

### ISSUE THREAD

**Issue by JasonFossen** [thoemmi/7Zip4Powershell#11]
With 7Zip4PowerShell 1.5.0, when I run the following commands in PoSh 5.0 on Windows 10:

Compress-7Zip -Path F:\folder -ArchiveFileName archive1.zip -CompressionMethod Deflate

Compress-7Zip -Path F:\folder -ArchiveFileName archive64.zip -CompressionMethod Deflate64

The two zip files are created successfully and Z-Zip can open them, but Windows File Explorer cannot open them.  The error message is "Windows cannot open the folder. The Compressed (zipped) Folder '...' is invalid."  The built-in PowerShell Expand-Archive cmdlet cannot open them either.

When these archives are opened in 7-Zip, the compression method shown is "LZMA:16", not "Deflate" or "Deflate64".  When I open zips created by File Explorer in 7-Zip, the compression method is "Deflate".

Other compression methods tested (BZip2, Ppmd, Lzma, Lzma2) create archives of the expected types when using "Compress-7Zip -CompressionMethod xxxx".  The "Default" method uses LZMA:16.

Note that when "-Format Zip" is used, then it defaults to Deflate as expected, and Deflate64 can also optionally be set as the compression method, and both such zip-format files can be opened in File Explorer without problems.

So, when -CompressionMethod is either Deflate or Deflate64, and -Format is not specified, should -Format default to Zip?  Should the other -CompressionMethod options also have associated -Format defaults when -Format is not explicitly given in order to avoid compatibility problems or error messages when sharing archives with people who are not using 7-Zip?

**Comment by thoemmi** [comment]
Hi @JasonFossen, I never validated the reuslt of the compression, as this module is just a wrapper around the [SevenZipSharp library](https://sevenzipsharp.codeplex.com/).

However, I was able to produce your issue. I ran following script:
```powershell
Import-Module 7Zip4PowerShell

$7z = "C:\Program Files\7-Zip\7z.exe"
$archiveFileName = "D:\demo\temp.bin"

$methods = 
    [SevenZip.CompressionMethod]::BZip2,
    [SevenZip.CompressionMethod]::Deflate,
    [SevenZip.CompressionMethod]::Deflate64,
    [SevenZip.CompressionMethod]::Lzma,
    [SevenZip.CompressionMethod]::Lzma2,
    [SevenZip.CompressionMethod]::Ppmd

$result = @{}
$methods | % {
    $method = $_

    Compress-7Zip -Path D:\folder -ArchiveFileName $archiveFileName -CompressionMethod $method | Out-Null

    $detectedMethod = & $7z t $archiveFileName | ? { $_ -match "Method = ([^$]*)" } | % { $matches[1] }

    $result.Add($method, $detectedMethod)
}
$result
```
This script outputs a table of the compression method passed to `Compress-7Zip` versus the actual method being used (detected by calling `7z.exe t <archive>`)
This is what I get:
```
Name                           Value
----                           -----
Ppmd                           PPMD BCJ
Lzma2                          LZMA2:12m BCJ
Lzma                           LZMA:12m BCJ
BZip2                          BZip2 BCJ
Deflate64                      LZMA:12m BCJ
Deflate                        LZMA:12m BCJ
```
I'll investigate the issue further.

BTW thanks for your donation 😃🍺

**Comment by thoemmi** [comment]
Haven't used my own module for some time 😔. In fact, valid `CompressionMethod`s depend on the selected `Format`. E.g. `Deflate` and `Deflate64` cannot be used with `SevenZip`.

Here's a table of valid combinations of formats and compression methods (according to SevenZipSharp's source code):

| Format | Compression methods |
| --- | --- | 
| SevenZip | Copy, BZip2, Lzma, Lzma2, Ppmd |
| Zip | Copy, Deflate, Deflate64, BZip2, Lzma, Lzma2 |
| GZip | Deflate |
| BZip2 | BZip2 |
| Tar | Copy |
| XZ | Copy, Deflate, Deflate64, BZip2, Lzma, Lzma2, Ppmd |

**Comment by JasonFossen** [comment]
I noticed that when using "-format sevenzip", the compression method is defaulting to PPMD.  Shouldn't it default to LZMA2 instead?

**Comment by thoemmi** [comment]
You're right. I cannot remember why I've chosen PPMd as default method. I'll change it to default (which in fact is LZMA2)
