### ISSUE TITLE
Compression level names don't match the graphical 7-Zip

### ISSUE THREAD

**Issue by JasonFossen** [thoemmi/7Zip4Powershell#12]
It would be slightly better if the arguments to -CompressionLevel in PowerShell matched the names of the compression levels in the 7-Zip graphical application.  (This might be an english language issue only.)

**Comment by thoemmi** [comment]
I don't maintain the level names myself. They originate from the SevenZipSharp library, see https://sevenzipsharp.codeplex.com/SourceControl/latest#SevenZip/Formats.cs.
