### ISSUE TITLE
WriteVerbose() instead of Write()

### ISSUE THREAD

**Issue by JasonFossen** [thoemmi/7Zip4Powershell#13]
Suggestion:  

1) Replace all the Write() with WriteVerbose() in the cmdlets, so that this ongoing status information is only displayed when using the -Verbose switch.  These verbose messages could optionally include more low-level information too, like compression method used, time transpired for each file, full path, etc.  The progress bar already gives a visual hint that work is being done in the background.

2) The compress/expand cmdlets should output nothing to the pipeline (just throw exceptions), just like Microsoft's Compress/Expand-Archive cmdlets.

**Comment by thoemmi** [comment]
I agree with you, texts should be written using `WriteVerbose`.

However, regarding displaying additional information: 
* to display the actual compression method, my code would have to open the archive **after** the compression has finished
* the API notifies me that a file was compressed, but not **which** file. I could remember the last started compression, but if 7z is using multiple threads, the notifications may interleave. Thus I cannot determine how long the compression of a specific file took.
