### ISSUE TITLE
Implement a -WhatIf switch

### ISSUE THREAD

**Issue by JasonFossen** [thoemmi/7Zip4Powershell#14]
Suggestion: 

Implement a -WhatIf switch that outputs the same info as when using -Verbose (using mostly the same code hopefully), but not actually do anything of course.  

This would be useful for testing a command that would overwrite existing files or that would take many minutes/hours to complete.

**Comment by thoemmi** [comment]
An useful suggestion, however that's not possible. There's no parameter where I could instruct 7z to only pretend the compression without actually writing anything to the target file.
