### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by rgel** [thoemmi/7Zip4Powershell#25]
Is it possible to add `-Split` parameter to split archives into fixed size peaces.
Like `-v700m` in the command line utility `7za.exe`.
Example: `7za.exe a .\arch.zip .\file.iso -v700m`.
Thanks

**Comment by thoemmi** [comment]
It's a good idea. Until I've implemented it, you can use following work-around:
```powershell
$initScript = {
    param ($compressor)
    $compressor.VolumeSize =700*1024*1024 
}

Compress-7Zip -Path . -ArchiveFileName demo.7z -CustomInitialization $initScript
```

**Comment by rgel** [comment]
Thanks, it would be nice.
The workaround was helpful.
