### ISSUE TITLE
Compress-7Zip : Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by pjkellar** [thoemmi/7Zip4Powershell#33]
Having an issues with Windows Server 2012 R2 and Compress-7Zip. Code looks like this:
`$AbsoluteSourcePath = C:\Path\To\Folder`
`$AbsoluteDestPath = C:\Path\To\Filename.zip`
`Compress-7Zip -Path $AbsoluteSourcePath -ArchiveFileName $AbsoluteDestPath -Format Zip -Password "password"`

The exceptions that gets thrown is:
Compress-7Zip : Index was outside the bounds of the array.
At C:\STSCO\Scripts\archiveDataForSTSCO.ps1:21 char:5
+     Compress-7Zip -Path $AbsoluteSourcePath -ArchiveFileName $Absolut ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (SevenZip4PowerS...+CompressWorker:CompressWorker) [Compress-7Zip], IndexOutOfRangeE 
   xception
    + FullyQualifiedErrorId : err01,SevenZip4PowerShell.Compress7Zip

I can't seem to figure out why this is occurring as the same script runs fine on my Windows 10 Anniversary Edition unit. Any information would be helpful.
Thank you.

**Comment by pjkellar** [comment]
Just as an update to this -- I removed the 1.7.0 version from the server and installed the 1.6.0 and the commands work as expected (and as they do on my Windows 10 workstation). I would speculate that the issue stems from the most recent update 1.7.0 and the `d6f783c` commit around line 101.

**Comment by thoemmi** [comment]
Thanks for reporting this issue. The exception occurs inside SevenZip, which is an external library. I'll investigate the issue.

**Comment by pjkellar** [comment]
Very impressed with the turn around time here. Thanks so much.

**Comment by thoemmi** [comment]
Hi @pjkellar, I just released a fixed version **[1.7.1](https://github.com/thoemmi/7Zip4Powershell/releases/tag/v1.7.1)**, published at [NuGet](https://www.nuget.org/packages/7Zip4Powershell/1.7.1) and [PowerShell Gallery](https://www.powershellgallery.com/packages/7Zip4Powershell/1.7.1). It was a very nasty oversight by me, thanks again for reporting.

**Comment by FenixVale** [comment]
I seem to be having this same issue on my own use of it in 1.9

Compress-7Zip -ArchiveFilename "\\192.168.30.24\UPD Archives\$Term$NameF.7z" -Path "\\192.168.30.24\UPD\" -filter "UVHD-$SID.vhdx" -CompressionLevel Fast
