### ISSUE TITLE
Can't use PowerShell encrypted passwords

### ISSUE THREAD

**Issue by GHRoss** [thoemmi/7Zip4Powershell#34]
At the moment we have a CSV file that contains various parameters for zipping and encrypting files, this file of course contains the encryption password.

We encrypt these passwords with PowerShell and then the script reads the passwords in when required.

7Zip4Powershell isn't currently able (from what I can tell) to decrypt PowerShell encrypted passwords securely, so we end up having to do something like this...

`[Runtime.InteropServices.Marshal]::PtrToStringAuto([Runtime.InteropServices.Marshal]::SecureStringToBSTR(($password | ConvertTo-SecureString))))`

The above will decrypt the encrypted password before it's parsed in, however this is insecure as the password is then in plain text so we would prefer to use a secure method like...

`$credential = New-Object System.Management.Automation.PSCredential $acquser,(Get-Content $password | ConvertTo-SecureString)`

It would be great if 7Zip4Powershell was capable of this.

**Comment by thoemmi** [comment]
I could add a `SecurePassword` parameter. However, that would just move the conversion from `SecureString` to a plain string inside the cmdlet. At least the script wouldn't see the insecure string anymore.

**Comment by GHRoss** [comment]
Would it be possible to make it decrypt the password securely? The suggested options seems like a bit of a pseudo fix? 

For what it's worth, the WinSCP module does this. https://github.com/dotps1/WinSCP

Perhaps there's something in their module that you could use?

**Comment by thoemmi** [comment]
@GHRoss I've added a `SecurePassword` parameter in 5e069738e135a5c2a883de9056e22a6987639b1e in a separate branch. It's of type `SecureString`, and will [converted to a regular string at runtime](https://github.com/thoemmi/7Zip4Powershell/commit/5e069738e135a5c2a883de9056e22a6987639b1e#diff-4e125a4ab75279207f86e9f21c75800fR92). Would this fulfill your requirement?

**Comment by GHRoss** [comment]
@thoemmi Yes it would, thank you very much.

**Comment by thoemmi** [comment]
The new `SecurePassword` parameter is implemented in version 1.8 of the module, published at [NuGet](https://www.nuget.org/packages/7Zip4Powershell/1.8.0) and [PowerShell Gallery](https://www.powershellgallery.com/packages/7Zip4Powershell/1.8.0).
