### ISSUE TITLE
custom Parameter dosn't work on Expand-7Zip

### ISSUE THREAD

**Issue by jmahmens** [thoemmi/7Zip4Powershell#37]
Using the following create an Error.
``` powershell  
$initScript = {  
    param ($extractor)  
    #$extractor.CustomParameters.Add("mt","off")  
    #$extractor.CustomParameters.Add("xr","!*.txt")  
    $extractor.CustomParameters.Add("x","r!*.txt")  
}  
$Ext72=Expand-7Zip -ArchiveFileName $ArchiveFileName.FullName -TargetPath $output2Dir -CustomInitialization $initScript -Debug -Verbose  
```
Expand-7Zip : Es ist nicht möglich, eine Methode für einen Ausdruck aufzurufen, der den NULL hat.  
In c:\temp\Extract.ps1:xx Zeichen:yy  
+ ...      $Ext72=Expand-7Zip -ArchiveFileName $ArchiveFileName.FullName -T ...  
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  
    + CategoryInfo          : NotSpecified: (SevenZip4PowerS...ip+ExpandWorker:ExpandWorker) [Expand-7Zip], RuntimeException  
    + FullyQualifiedErrorId : err01,SevenZip4PowerShell.Expand7Zip  

I have to check the Sourcecode for the right Parameter because ``compressor`` from example dosn't work.  
I tried to do something like this:
``7z.exe x Demo.7z -xr!*txt -oDemo2``
and exclude all *.txt files from Archive.

**Comment by thoemmi** [comment]
I'm afraid the library I'm using does not support custom parameters for the extractor. It's a feature available only for the compressor.

Therefore I have to announce that I am going to remove the `CustomInitialization` from `Expand-7Zip` in the next release.
