### ISSUE TITLE
Add support for CustomParameters (SevenZipSharp)

### ISSUE THREAD

**Issue by ghostsquad** [thoemmi/7Zip4Powershell#4]
the custom parameters dictionary property of SevenZipCompressor I believe is how you can pass in switches:

http://sevenzip.sourceforge.jp/chm/cmdline/switches/method.htm

I think the most important one is 

mt=[off | on | {N}]
Sets multithread mode. If you have a multiprocessor or multicore system, you can get a speed increase with this switch. This option affects only compression (with any method) and decompression of BZip2 streams. Each thread in the multithread mode uses 32 MB of RAM for buffering. If you specify {N}, 7-Zip tries to use N threads.

**Comment by thoemmi** [comment]
Thanks for your suggestion. I implemented that in v1.2, which I released a few minutes ago.

You can now add custom parameters by passing a scriptblock:
```powershell
$initScript = {
    param ($compressor)
    $compressor.CustomParameters.Add("mt", "off")
}

Compress-7Zip -Path . -ArchiveFileName demo.7z -CustomInitialization $initScript
```

**Comment by ghostsquad** [comment]
:+1:  :100:

**Comment by ghostsquad** [comment]
did you make sure to update the documentation?

**Comment by thoemmi** [comment]
Yes, I've added the same snippet to the readme.
