### ISSUE TITLE
Security Vulnerabilities with 7Zip DLLs 

### ISSUE THREAD

**Issue by compuman37** [thoemmi/7Zip4Powershell#41]
Looking at the 7Zip4Powershell repo indicates that the included 7Zip DLLs are about 5 years old. Since then there have been many security [vulnerabilities](https://www.cvedetails.com/vulnerability-list/vendor_id-9220/7-zip.html) identified with 7Zip. Can the 7Zip DLLs included in this project be updated to their latest available versions?

**Comment by compuman37** [comment]
Are there any plans to incorporate the latest 7Zip DLLs into this project?

**Comment by thoemmi** [comment]
Yes, I'll include them in the next release (no date yet though)

**Comment by compuman37** [comment]
Thanks thoemmi.

**Comment by thoemmi** [comment]
Fixed in fdaaa0635a8aa9d1c662f6a20747594e5653686d. However, due to time constraints I won't be able to release it before September.

**Comment by janis-veinbergs** [comment]
This probably needs another verison bump. The [list of vulnerabilities](https://www.cvedetails.com/vulnerability-list/vendor_id-9220/7-zip.html) has grew a lot since mid 2017

**Comment by thoemmi** [comment]
Fixed in #56
