### ISSUE TITLE
Unable to specify AES-256 as an encryption method

### ISSUE THREAD

**Issue by JoeJe1993** [thoemmi/7Zip4Powershell#42]
When using ```Compress-7zip``` to create an encrypted archive, there's no way to specify AES-256 when creating *.zip archives. The module automatically defaults to ZipCrypto which has proven to be a weak cipher.

**Comment by JoeJe1993** [comment]
Bump

**Comment by thoemmi** [comment]
You can specify additional settings using a script,
```powershell
$initScript = {
    param ($compressor)
    $compressor.CustomParameters.Add("em", "AES256")
}
Compress-7Zip -Path . -ArchiveFileName demo.zip -CustomInitialization $initScript
```
See https://sevenzip.osdn.jp/chm/cmdline/switches/method.htm for all switches supported by 7-Zip.

**Comment by JoeJe1993** [comment]
Thanks, this resolved my problem. Could this be made as a switch with predefined options?

**Comment by thoemmi** [comment]
If I added a parameter for each and every option, you wouldn't see the forest for the trees. 😉
