### ISSUE TITLE
When using volumesize archive files aren't created

### ISSUE THREAD

**Issue by MaikelvanGorkom** [thoemmi/7Zip4Powershell#44]
Hi,

I'm trying to use the module. Everything works great, except when i try to use -VolumeSize with what ever parameter (from 1 to 10000) is just doesn't create the archives. It says it does, but when i check nothing is made. Even tried it with verbose on, and the message "VERBOSE: Compression finished" shows, but no archives.

When i don't give the parameter volumesize i get:
VERBOSE: 1 files found for compression
VERBOSE: Compressing Archive.7z
VERBOSE: Compression finished

With the parameter volumesize i only get:
VERBOSE: Compression finished

Am i overlooking something?

**Comment by MaikelvanGorkom** [comment]
Been testing a bit more and it looks like the parameter just doesn't seem to work and even seem to disable the creation of the target file.

Anybody an idea?

**Comment by thoemmi** [comment]
I've tested it on my machine. Actually, it works when you pass a folder to `-Path`.  On the other hand, if you specify a single file, it doesn't work, like in your case. I'm afraid that the issue is caused by the library I'm using.

**Comment by MaikelvanGorkom** [comment]
Thanks, will test that, it will fit the purpose if i need to use path.

**Comment by MaikelvanGorkom** [comment]
That was the solution!!
