### ISSUE TITLE
Increase memory used for compression

### ISSUE THREAD

**Issue by kalandarisvili** [thoemmi/7Zip4Powershell#49]
Thank you for this module! 
I am trying to incorporate this script into a database backup script. Since I have 40GB worth of SQL .bak files to be zipped an compressed - I am wondering how to give it more resources? 
Could you please exemplify how to give more memory to it? It now uses only 300Mb for the compression.

**Comment by thoemmi** [comment]
You can set several parameters of the underlying 7Z library by using a script. E.g. you can disable multithreading this way:
```powershell
$initScript = {
    param ($compressor)
    $compressor.CustomParameters.Add("mt", "off")
}

Compress-7Zip -Path . -ArchiveFileName demo.zip -CustomInitialization $initScript
```
A list of all supported parameters is listed [here](https://sevenzip.osdn.jp/chm/cmdline/switches/method.htm).
