### ISSUE TITLE
Support for progress event hooks

### ISSUE THREAD

**Issue by ghostsquad** [thoemmi/7Zip4Powershell#5]
The current implementation is great if there is a human looking at the console. If these cmdlets are wrapped in a script, and there was a need make decisions about the progress being made (such as logging or timeout), that's not currently possible.

**Comment by thoemmi** [comment]
I'm afraid I don't understand. The current implementation calls [`Cmdlet.WriteProgress`](https://msdn.microsoft.com/en-us/library/system.management.automation.cmdlet.writeprogress(v=vs.85).aspx). It's up to the host to handle the progress, i.e. the Powershell command line shows a progress bar.

**Comment by ghostsquad** [comment]
What I mean is being able to expose the event hooks as seen below to the client

```CSharp
var currentStatus = "Compressing";
                compressor.FilesFound += (sender, args) =>
                    Write(String.Format("{0} files found for compression", args.Value));
                compressor.Compressing += (sender, args) =>
                    WriteProgress(new ProgressRecord(0, activity, currentStatus) { PercentComplete = args.PercentDone });
                compressor.FileCompressionStarted += (sender, args) => {
                    currentStatus = String.Format("Compressing {0}", args.FileName);
                    Write(String.Format("Compressing {0}", args.FileName));
```
This could be done by allowing the client to pass in a scriptblock or action delegate, and that delegate is called at the same time as WriteProgress.

**Comment by thoemmi** [comment]
Sorry for letting you wait for so long.

Some time ago I introduced an additional parameter, allowing the user to provide a scriptblock. This would be called before the (de)compression starts (see #4).

With that feature and `Register-ObjectEvent` you can add your own hooks:
```powershell
$initScript = {
    param ($compressor)

    Register-ObjectEvent -InputObject $compressor -EventName "FileCompressionStarted" -Action { ... }
    Register-ObjectEvent -InputObject $compressor -EventName "Compressing" -Action { ... }
}

Compress-7Zip -CustomInitialization $initScript ...
```
