### ISSUE TITLE
The execution has failed due to the bug in the SevenZipSharp

### ISSUE THREAD

**Issue by EmbeddedBacon** [thoemmi/7Zip4Powershell#54]
Hello,

  I have a batch file that issues ssh and scp commands (after installing OpenSSH) to tar/compress a directory on the Linux machine then copied to the Windows 10 machine.  I have these parts working.  I found this module may be imported and used to decompress the tar.  When the script executes the following is seen on the console:

```
Expand-7Zip : The execution has failed due to the bug in the SevenZipSharp.
Please report about it to http://sevenzipsharp.codeplex.com/WorkItem/List.aspx, post the release number and attach the archive.
At line:1 char:1
+ Expand-7Zip -ArchiveFileName repo_2018-12-21_1614.tar.gz -Targ ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (SevenZip4PowerS...ip+ExpandWorker:ExpandWorker) [Expand-7Zip], SevenZipException
    + FullyQualifiedErrorId : err01,SevenZip4PowerShell.Expand7Zip
```

I am able to view the tar file using WinRAR, so I believe the file is not corrupt.  Any idea what I am doing wrong?

Thanks,
Mark

**Comment by jasonmcboyd** [comment]
I'm experiencing the same issue. I'm not sure what the  problem is but I noticed that if I only archive the files without compressing (create a .tar instead of a .tar.gz) I am able to extract the .tar file when it is copied to the Windows box.

**Comment by jasonmcboyd** [comment]
@EmbeddedBacon It's possible. I pop in to several different .NET meetups in the Bay area occasionally.

**Comment by EmbeddedBacon** [comment]
@jasonmcboyd, now I know where.  Did you happen to back the Kiwi4 Kickstarter campaign???  If you are the same person, then you are the one who has been fighting for us backers.  My name under Kickstarter is simple "Mark".

**Comment by thoemmi** [comment]
The wrapper around 7zip has been changed from SevenZipSharp to Squid-Box.SevenZipSharp back in June in #57 . 
Maybe this bug has gone with this switch. Otherwise we can re-open this issue.
