### ISSUE TITLE
.app archive not expanding with powershell module but with 7z.exe

### ISSUE THREAD

**Issue by staedter** [thoemmi/7Zip4Powershell#59]
I am currently trying to automate some stuff regarding our app packages with are compressed into an exotic archive with the extension .app

When I'm using the 7Zip GUI I can just open and/or extract the archive to get at the files inside. But when I'm trying to use the powershell module I get the following error when I try to expand-7z the .app file:

`Expand-7Zip : Extension "app" is not a supported archive file name extension.`

I already found a "workaround" if I just use the command-line functionality for the 7z.exe (`& 'C:\Program Files\7-Zip\7z.exe' x '.\our_app_3.0.7.0.app' -o*`) but that would require me to make sure that I install the necessary Program on our build slaves and I would much rather just stay with using only powershell modules.

I was wondering if there is any way I could make the ps module behave like the exe or if it is something that the dll is not able to do?

Any answer would be greatly appreciated :)

**Comment by staedter** [comment]
Anyone? Anyone? Bueller? Anyone?

**Comment by thoemmi** [comment]
7Zip4Powershell uses [SevenZipSharp](https://github.com/squid-box/SevenZipSharp), a managed wrapper around 7z.dll. I'm afraid its [FileChecker](https://github.com/squid-box/SevenZipSharp/blob/dev/SevenZip/FileChecker.cs) does not know how to handle _.app_ files.
