### ISSUE TITLE
Consider Hosting on PowerShell Gallery

### ISSUE THREAD

**Issue by aolszowka** [thoemmi/7Zip4Powershell#6]
This would be a great project to have posted up on the new PowerShell Gallery! (think NuGet but for PowerShell Extensions). It shouldn't take too much to port this over https://www.powershellgallery.com/

**Comment by thoemmi** [comment]
Thanks for your suggestion. I'll make it a "real" PowerShell module and upload it to PowerShell Gallery.

**Comment by thoemmi** [comment]
The PowerShell module is now available in the PowerShell Gallery: https://www.powershellgallery.com/packages/7Zip4Powershell

**Comment by aolszowka** [comment]
Thank you!
