### ISSUE TITLE
Does not work in Powershell on Linux

### ISSUE THREAD

**Issue by millerad7** [thoemmi/7Zip4Powershell#62]
Compress-7Zip: Unable to load shared library 'kernel32.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libkernel32.dll: cannot open shared object file: No such file or directory

This is with p7zip installed on Linux as well.  I am not sure if there is a way to fix this problem, but it is inconvenient since it broke my script once I moved it to Linux.

**Comment by thoemmi** [comment]
That‘s by design. This module uses a Win32 dll for 7z.
