### ISSUE TITLE
Only extrac some files in the 7z package

### ISSUE THREAD

**Issue by msjzs** [thoemmi/7Zip4Powershell#66]
Hi, there，Can I only get some files in the 7z pakage
Here is my 7z pakage:
C:\test.7z
C:\test.7z\c.docx
C:\test.7z\666\666.jpg
C:\test.7z\666\current.docx

Now, I only want to extrat 666.jpg

**Comment by thoemmi** [comment]
No, that's not possible. 7Zip4Powershell can only extract the complete archive.
