### ISSUE TITLE
SevenZipSharp.dll is missing in 2.0.0 pre-release version causing module import to fail

### ISSUE THREAD

**Issue by kborowinski** [thoemmi/7Zip4Powershell#70]
@thoemmi  *SevenZipSharp.dll* is missing in 7Zip4Poweshell 2.0.0 pre-release causing module import to fail:

![image](https://user-images.githubusercontent.com/16168755/99395036-272d5600-28e0-11eb-8059-abdbea0fb417.png)

2.0.0 folder content:
![image](https://user-images.githubusercontent.com/16168755/99395099-3e6c4380-28e0-11eb-8469-3af68fda572b.png)

1.13.0 folder content:
![image](https://user-images.githubusercontent.com/16168755/99395283-7e332b00-28e0-11eb-9087-a82b5b85e49b.png)

**Workaround:**

1. Download missing package from NuGet:
https://www.nuget.org/packages/Squid-Box.SevenZipSharp/

2. Extract *SevenZipSharp.dll* from *netstandard2.0* folder and copy it to the module installation folder

**Comment by thoemmi** [comment]
Good catch @kborowinski, thanks for reporting. I've published an update.

**Comment by kborowinski** [comment]
@thoemmi Unfortunately it looks like there's a deeper problem with 2.0.0. I've updated to latest version but it fails on PS 5.1 when creating an archive with following error:

![image](https://user-images.githubusercontent.com/16168755/99407812-d0c81380-28ef-11eb-93b9-8e9af0929c54.png)

And on PS 7.1 it fails silently (no error, but archive is not created):

![image](https://user-images.githubusercontent.com/16168755/99407751-c0179d80-28ef-11eb-8151-8bd1b112c12f.png)

**Comment by thoemmi** [comment]
\*sigh\* Ok, thanks for trying this. I'll spend some tome tonight on this. If I can fix it, fine. If not, I'll revoke the support of PowerShell Core.

**Comment by thoemmi** [comment]
It turned out the issue is caused by the SevenZipSharp library 🙄 I've sent them a bug fix.

**Comment by thoemmi** [comment]
BTW, I have unlisted the 7Zip4PowerShell prereleases from yesterday.

**Comment by squid-box** [comment]
@thoemmi Sorry for the delay, I've finally gotten around to release a version with your fix included. 

Let me know if 1.3.318 still didn't fix this for you.

**Comment by kborowinski** [comment]
@thoemmi I've just closed my PR that was updating the NuGet packages to the latest versions. I didn't notice that my fork was way behind your master, sorry.

BTW the new version of *Squid-Box.SevenZipSharp* includes your *[lazy 7zip.dll path PR](https://github.com/squid-box/SevenZipSharp/pull/111/commits/4927c53ea83de84274c7da390e153c56fce5e24b)*. It should fix the https://github.com/thoemmi/7Zip4Powershell/issues/70#issuecomment-729256544 and allow you to republish the test version of *7Zip4PowerShell 2.0.0* for PowerShell Core, if you wish.

**Comment by thoemmi** [comment]
@squid-box Thanks for accepting my PR, much appreciated. I've updated the package reference to the most recent version, 1.4.0.345.

@kborowinski I have published a new pre-release module with the updated Squid-Box.SevenZipSharp, https://www.powershellgallery.com/packages/7Zip4Powershell/2.0.0-beta0009. Feel free to give it a try.

Thank you all for your patience. This Powershell module does not have a high priority on my list, so it always takes me a while until I react.

**Comment by kborowinski** [comment]
@thoemmi No problems with *2.0.0-beta0009* so far but please give me another week for testing before making official release.

**Comment by kborowinski** [comment]
@thoemmi I didn't find any problems. If nobody else has reported any issues you can publish official release I think.

**Comment by thoemmi** [comment]
Thanks for testing, @kborowinski, much appreciated :+1: 
I have just published v2.0 to the PowerShell Gallery.
