### ISSUE TITLE
Parameter -VolumeSize only Int32

### ISSUE THREAD

**Issue by AndyGss** [thoemmi/7Zip4Powershell#71]
I like this Powershell-module and I use it very often.

Is there an chance to extend the parameter -VolumeSize to Int64 (to compress bigger archives)?

Thankx 
AndyGss

**Comment by thoemmi** [comment]
Hi @AndyGss, I've changed the type to `long` in the prerelease version, https://www.powershellgallery.com/packages/7Zip4Powershell/2.0.0-beta0009

Thanks for your patience.
