### ISSUE TITLE
Module not respecting temp/working directory settings

### ISSUE THREAD

**Issue by paradizelost** [thoemmi/7Zip4Powershell#78]
The module is using %temp% directory for working space regardless of what is set in the 7zip program, and has no way to specify on the command line that i can find. It is not an option that is part of the custom initialization script from what i can tell either. This is causing large archive operations to fill c: drives on systems when there is ample space on the drive the archive is being placed.

**Comment by chrisdiphoorn** [comment]
**Change the %temp% environment value for the User Account which is running the process.**
Logon to the server with the account, Right-click This PC and click Properties, Click Advanced System Settings and then click Environment Variables. Select the TEMP variable and click Edit. TEMP and TMP might be defined as system variables or user variables, depending on how your system is set up. In the Variable value box, type the new folder location and click OK.
For example, type c:\temp.
Log off, and test

**Comment by thoemmi** [comment]
Version [v2.3.0](https://www.powershellgallery.com/packages/7Zip4Powershell/2.3.0) of 7Zip4Powershell adds an optional `TempFolder` parameter to `Compress-7Zip`.
