### ISSUE TITLE
Archive Password Support?

### ISSUE THREAD

**Issue by onyxhat** [thoemmi/7Zip4Powershell#8]
**Never mind - was able to add this for my fork - consider it closed**

Do you have plans to add password support for archives, or is there any way to do this via the CustomInitialization script?

**Comment by thoemmi** [comment]
Great idea. Unfortunately it's not possible via `CustomInitialization`. I'll add password support to the cmdlets.

**Comment by thoemmi** [comment]
I've added password support in [version 1.3](https://github.com/thoemmi/7Zip4Powershell/releases/tag/v1.3).
