### ISSUE TITLE
Did not find the function of writing new files to the existing archive

### ISSUE THREAD

**Issue by arafelp** [thoemmi/7Zip4Powershell#86]
Tell me, please, whether such a function is implemented for 7zip archives?
with the Compress-7Zip command, create an archive with a name, for example, 1. Next, you need to add other files there, in the same archive, but the next command simply overwrites new files, and does not add them

**Comment by thoemmi** [comment]
Hi @arafelp, you have to add the switch `-append` to `Compress-7Zip`.

**Comment by arafelp** [comment]
Oh thank you!!!
