### ISSUE TITLE
NullReferenceException on PS 7.4.0 when extracting multiple 7zip archives simultaneously 

### ISSUE THREAD

**Issue by kborowinski** [thoemmi/7Zip4Powershell#88]
@thoemmi:  As per title, *NullReferenceException* on PS 7.4.0 when extracting multiple 7zip archives simultaneously. This happens only when progress bar is visible - `$ProgressPreference = Continue`

*I'm just reporting it here for the reference as I'm working on the fix already, and will submit PR soon.*

1. Excerpt from a function using `Start-ThreadJob` to expand multiple 7zip archives simulteneously:
![image](https://github.com/thoemmi/7Zip4Powershell/assets/16168755/efa0d850-2441-40c5-88c7-a7c29cb09d88)

2. Function output with NRE marked in the red box:
![image](https://github.com/thoemmi/7Zip4Powershell/assets/16168755/6f338bfe-a3f3-41b4-9291-597bde0ec83c)

3. NRE details:
![image](https://github.com/thoemmi/7Zip4Powershell/assets/16168755/42cedbfa-b55a-413f-a955-e927ebb39adc)

**WORKAROUND:**
Disable progress bar with `$ProgressPreference = SilentlyContinue` before calling the `Expand-7zip` cmdlet

**Comment by thoemmi** [comment]
fixed in #89
